### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/search_engine#10]
I'm wondering if running our website as a docker or singularity container is an option. Because our installattion instructions are a bit complicated, and they could be fully automated using docker.

This could be a starting point:
https://dev.to/paschalogu/how-i-deployed-my-website-as-a-container-3fje

**Comment by SeverusYixin** [comment]
I've learnt a bit about docker configuration, but I'm currently experiencing some logic bugs on the searchresultpage, and when I'm done with that will try to build our site on docker!

**Comment by SeverusYixin** [comment]
We can assume a time plan to deploy it on docker :)

**Comment by SeverusYixin** [comment]
auto make all the installation

**Comment by SeverusYixin** [comment]
Check how to give or share the docker container to others
