### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/search_engine#14]
It would be great if the search website looks similar to the https://NFDI4BioImage.de website

**Comment by SeverusYixin** [comment]
Welcome to our newest search engine model! It's still a work in progress, and we would love your help to make it better. If you have any suggestions or feature requests, please share your valuable feedback. Thank you for your support!
![Homepage](https://github.com/user-attachments/assets/fcc0e08f-9111-4ef8-96c2-d850e57558db)
![search_result](https://github.com/user-attachments/assets/6f6f26c3-5b1a-4e80-bf4d-995a5986fda7)

**Comment by SeverusYixin** [comment]
If you have more suggestions for logos or backgrounds, please also send them to me!
