### ISSUE TITLE
Ensure that submission of new entries does not modify old entries

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/search_engine#55]
During the demo with the NFDI4BioImage TA5 meeting, a new entry was submitted to our database in this PR: https://github.com/NFDI4BIOIMAGE/training/pull/213

Unfortunately, this modifies many other entries too. We had the same issue in the AppSubmitter, so the solution should be similar. I presume this commit might help:
https://github.com/NFDI4BIOIMAGE/training/commit/463931163057f268644cdc07d262d94a68c25629

**Comment by SeverusYixin** [comment]
good idea, let me try it, maybe they use the different kinds of the write(normalize) version
